{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using gpu device 0: Tesla K40c (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5105)\n",
      "/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:601: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.\n",
      "  warnings.warn(warn)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using cuda_convnet (faster)\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import numpy as np\n",
    "import theano\n",
    "import lasagne\n",
    "import theano.tensor as T\n",
    "from helpers.mnist_dataset import load_mnist_rot, test_mnist_rot\n",
    "from helpers.Models import build_st_network\n",
    "from helpers.utils import iterate_minibatches"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Parameters\n",
    "BATCH_SIZE = 100\n",
    "EPOCH = 100\n",
    "BINS = np.linspace(-3, 3, 100)\n",
    "DISCRETE = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['mnist_all_rotation_normalized_float_train_valid.amat', 'mnist_all_rotation_normalized_float_test.amat']\n",
      "['mnist_all_rotation_normalized_float_train_valid.amat', 'mnist_all_rotation_normalized_float_test.amat']\n"
     ]
    }
   ],
   "source": [
    "# Load Dataset\n",
    "X_train, y_train, X_val, y_val = load_mnist_rot(path='mnist_rotation_new.zip', which='train')\n",
    "Xtst, Ytst = load_mnist_rot(path='mnist_rotation_new.zip', which='test')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "# Build the model, and place holders\n",
    "network = build_st_network(b_size=BATCH_SIZE,\n",
    "                           bins_choose=BINS,\n",
    "                           withdiscrete=DISCRETE,\n",
    "                           input_shape=X_train.shape)\n",
    "\n",
    "X = T.tensor4('inputs', dtype='float32')\n",
    "Y = T.ivector('targets')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Different Cost and outputs\n",
    "* The cost in update function and train function are using the cont. weights\n",
    "* The test and eval. functions are using the disc. weights"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "# Loss is continious\n",
    "prediction_cont = lasagne.layers.get_output(network, X, deterministic=False, withdiscrete=False)\n",
    "loss_cont = T.mean(lasagne.objectives.categorical_crossentropy(prediction_cont, Y), dtype='float32')\n",
    "\n",
    "prediction_disc = lasagne.layers.get_output(network, X, deterministic=False, withdiscrete=True)\n",
    "loss_disc = T.mean(lasagne.objectives.categorical_crossentropy(prediction_disc, Y), dtype='float32')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 12, 12), kshp=(32, 32, 5, 5), filter_dilation=(1, 1)}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: local_conv2d_gpu_conv\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5), filter_dilation=(1, 1)}(DimShuffle{0,3,1,2}.0, HostFromGpu.0)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/opt.py\", line 1820, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py\", line 2745, in local_conv2d_gpu_conv\n",
      "    inps[0] = as_cuda_ndarray_variable(inps[0])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 46, in as_cuda_ndarray_variable\n",
      "    return gpu_from_host(tensor_x)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/op.py\", line 602, in __call__\n",
      "    node = self.make_node(*inputs, **kwargs)\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py\", line 139, in make_node\n",
      "    dtype=x.dtype)()])\n",
      "  File \"/home/ilker/anaconda2/envs/theano/lib/python2.7/site-packages/theano/sandbox/cuda/type.py\", line 95, in __init__\n",
      "    (self.__class__.__name__, dtype, name))\n",
      "TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Get parameters, set update rule and create functions\n",
    "params = lasagne.layers.get_all_params(network, trainable=True)\n",
    "# We shall use the cont. cost in update function\n",
    "updates = lasagne.updates.nesterov_momentum(loss_cont, params,\n",
    "                                            learning_rate=0.01, momentum=0.9)\n",
    "# Test function\n",
    "# Test_prediction is on discrete values\n",
    "test_prediction = lasagne.layers.get_output(network, X, deterministic=True, withdiscrete=True)\n",
    "test_loss = T.mean(lasagne.objectives.categorical_crossentropy(test_prediction, Y), dtype='float32')\n",
    "test_acc = T.mean(T.eq(T.argmax(test_prediction, axis=1), Y), dtype='float32')\n",
    "val_fn = theano.function([X, Y], [test_loss, test_acc], allow_input_downcast=True)\n",
    "\n",
    "# Train function\n",
    "train_fn = theano.function([X, Y], loss_disc, updates=updates, allow_input_downcast=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "# Finally, launch the training loop.\n",
    "print(\"Starting training...\")\n",
    "# We iterate over epochs:\n",
    "for epoch in range(EPOCH):\n",
    "    # In each epoch, we do a full pass over the training data:\n",
    "    train_err = 0\n",
    "    train_batches = 0\n",
    "    start_time = time.time()\n",
    "    for batch in iterate_minibatches(X_train, y_train, BATCH_SIZE, shuffle=True):\n",
    "        inputs, targets = batch\n",
    "        train_err += train_fn(inputs, targets)\n",
    "        train_batches += 1\n",
    "\n",
    "    # And a full pass over the validation data:\n",
    "    val_err = 0\n",
    "    val_acc = 0\n",
    "    val_batches = 0\n",
    "    for batch in iterate_minibatches(X_val, y_val, BATCH_SIZE, shuffle=False):\n",
    "        inputs, targets = batch\n",
    "        err, acc = val_fn(inputs, targets)\n",
    "        val_err += err\n",
    "        val_acc += acc\n",
    "        val_batches += 1\n",
    "\n",
    "    # Then we print the results for this epoch:\n",
    "    print(\"Epoch {} of {} took {:.3f}s\".format(\n",
    "        epoch + 1, EPOCH, time.time() - start_time))\n",
    "    print(\"  training loss:\\t\\t{:.6f}\".format(train_err / train_batches))\n",
    "    print(\"  validation loss:\\t\\t{:.6f}\".format(val_err / val_batches))\n",
    "    print(\"  validation accuracy:\\t\\t{:.2f} %\".format(\n",
    "        val_acc / val_batches * 100))\n",
    "\n",
    "# After training, we compute and print the test error:\n",
    "test_err = 0\n",
    "test_acc = 0\n",
    "test_batches = 0\n",
    "for batch in iterate_minibatches(X_test, y_test, BATCH_SIZE, shuffle=False):\n",
    "    inputs, targets = batch\n",
    "    err, acc = val_fn(inputs, targets)\n",
    "    test_err += err\n",
    "    test_acc += acc\n",
    "    test_batches += 1\n",
    "print(\"Final results:\")\n",
    "print(\"  test loss:\\t\\t\\t{:.6f}\".format(test_err / test_batches))\n",
    "print(\"  test accuracy:\\t\\t{:.2f} %\".format(\n",
    "    test_acc / test_batches * 100))"
   ]
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python [default]",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
